### PR TITLE
Fix build size and replace webpack with rollup

### PR DESCRIPTION
**Pull request by ritz078**
- A significant decrease in file size
- UMD build can now directly be served by unpkg
- CJS, UMD and ES6 build

### CODE REVIEW

**Comment by iqnivek** [comment]
Nice - yeah I realize that there's something off about the webpack configuration causing a large build size. Using Rollup was on my immediate todo list too, so this is great.

Will review and make a few tweaks as soon as possible (probably this week).

**Comment by iqnivek** [comment]
Made a few additional changes:

* Tweaked main/module/unpkg filenames
* Moved build folder from /build to /dist
* Minor changes to rollup config

@ritz078 thanks for the contribution! 🎉 Glad to be using rollup now.

**Comment by iqnivek** [comment]
Published in v2.0.1.

**Comment by ritz078** [comment]
@iqnivek Since you removed the filesize plugin, how do you track the bundle size during development ?

**Comment by iqnivek** [comment]
I had just been checking the file sizes in the dist folder, but yeah the plugin does seem useful for development. I'll add it back in in #28

**Pull request merged**
